### ISSUE TITLE
Feedback Review 3

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#103]
- [x] Vorlauf und Rücklauftemperatur konstant (=> Nothing changed. Man kann Konstanten angeben.)
- [x] Formel Massenstrom oder Aufteilung Wärmeprofil falsch. (Winter höher als Sommer)
- [x] Arbeitszeit anders protokollieren
- [x] FE: Validierung direkt wenn Node bestätigt wird
- [x] FE:  OutputNode/Entnahmestelle Label Warmwasserbedarf -> Wärmebedarf
- [x] FE: OutputNode/Entnahmestelle Fehlendes Label für Lastprofil Selection Box
- [x] FE: OutputNode/Entnahmestelle prüfen, ob Lastprofil/profileName immer übernommen wird
- [x] FE: Diagramme bei vielen Datenpunkten nur jeden xten Datenpunkt plotten (Performance)
- [x] FE: Eingabe Meta Daten vor Editor (Editor sperren, bis die Werte eingegeben sind) // UX verbessern
- [ ] Prüfen: Lastprofil bei Ändern fehlerhaft (Aussage JB)
- [x] Für Druckverlust bedarf es Durchmesser (dieser muss zuerst optimiert werden)
- [x] Kotlin with numpy (?) Schneller???

**Comment by EinfachGustav** [comment]
Seltsam. Das SLP wird bei mir ganz normal übernommen

**Comment by V3lop5** [comment]
@EinfachGustav auch beim Ändern?

**Comment by einfachMel** [comment]
Der Output-Knoten hat immer noch das Label Warmwasserbedarf

**Comment by einfachMel** [comment]
Nach dem Erstellen eines Output-Knotens kann dieser nicht ans restliche Netz angeschlossen werden. Ändert man danach das SLP oder geht nochmal in die Einstellung und wechselt hin und her, funktioniert die Anbindung.

**Comment by einfachMel** [comment]
Beim Klick auf den Button "Massenstrom bestimmen" passiert nix. Das Bild lädt kurz, die Ansicht ist aber dann wie vorher und in den Reiter Max Massenstrom kann nicht gewechselt werden.

**Comment by einfachMel** [comment]
Nachdem man eine 2. Input-Node hinzufügen wollte - was nicht funktioniert (wie in Fehlermeldung)- und danach noch eine Intermediate-/Output-Node angelegt werden soll, erscheint immer die Fehlermeldung, dass das Anlegen einer 2.InputNode nicht möglich ist
