### ISSUE TITLE
Formelcheck - Druckverluste Rohrleitung

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#184]
Ich glaube es ist sinnvoll das Lambda immer zu berechnen.

Dazu müssen wir Re bestimmen und noch weitere Berechnungen durchführen. Yippie

**Comment by V3lop5** [comment]
@einfachMel die Formel müsste noch in die Formelsammlung

**Comment by einfachMel** [comment]
Formel ist in der Formelsammlung drin
