### ISSUE TITLE
CSV Input for Temperaturzeitreihe

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#25]
Im Frontend soll eine CSV entgegen nehmen und 8760 Temperaturwerte (Stundenscharf) speichern.

**Comment by EinfachGustav** [comment]
feature/upload-csv 

Kann CSV Dateien per Drag & Drop einlesen
Diese werden allerdings nicht weiterverarbeitet

**Comment by V3lop5** [comment]
Wird vorerst nicht weiterentwickelt.

Man muss mit den voreingestellten Temperaturzeitreihen leben. Sorry :/
