### ISSUE TITLE
SLP Profile für Gas + Stundenwerte

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#39]
Die Standardlastprofile sollen auf Stundenbasis sein und für Gas.

Müssen rausgesucht werden und in Form einer CSV Datei gebracht werden.

Die bisher verwendete [CSV ](https://github.com/fhac-ewi/grid-optimizer/blob/main/resources/standard-load-profiles.csv) mit Strom SLP auf Tagesbasis ist falsch. Diese muss ersetzt werden.

**Comment by V3lop5** [comment]
Das gestaltet sich offensichtlich schwieriger... Man findet nicht so einfach ein Profil....

**Comment by V3lop5** [comment]
[Bsp Lastprofil Wärme EFH, MFH.xlsx](https://github.com/fhac-ewi/grid-optimizer/files/6430747/Bsp.Lastprofil.Warme.EFH.MFH.xlsx)

In diesem Dokument stehen für EFH und MFH (Einfamilien/Mehrfamilienhaus) die Werte zur Berechnung der täglichen Kurve drinnen.
`H-Profil` Werte für A, B, C, D, E, zero, mH, bH, mW, bW

Zudem stehen dort für jede EFH die Aufteilung der Wärme auf einen Tag in Abhängigkeit der Außentemperatur. `Stundenfaktoren EFH`

Bitte daraus eine CSV Datei im Format 
Zeile 1: `A; B; C; D; E; zero; mH; bH; mW; bW;`
Zeile 2-n: `<Temperatur von Inklusive>;<Temperatur bis inklusive>;<Prozent Stunde 6:00>;....;<Prozent Stunde 5>;`
erstellen.

Pro Art eine CSV Datei.
Also `EFH.csv` und `MFH.csv`, ggf weitere.

**Comment by einfachMel** [comment]
Hoffentlich so wie geplant erledigt. Liegen im EWI-Share im Ordner Planung und Bewertung von Energienetzen
