### ISSUE TITLE
Formel Massenstrom korrigieren

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#40]
In der [bisherigen Formel](https://github.com/fhac-ewi/grid-optimizer/blob/37cdf58b219793a7706d32c05914154e1553b520/src/util/MathUtil.kt#L18) für Massenstrom fehlt die spezifische Wärmekapazität in Abhängigkeit der Temperatur.

Die Formel muss korrigiert werden.

Zusätzlich würden ein oder zwei Beispiele mit konkreten Zahlen nicht schaden. Dann können diese für Tests genutzt werden.

Ich habe:
- Vorlauftemperatur in °C
- Rücklauftemperatur in °C
- Energiebedarf in kW

Ergebnis: Massenstrom in kg/h?

**Comment by einfachMel** [comment]
Formel (Formel Massenstrom und Wärmeleistung) ist im Wiki geupdatet. [hier](https://github.com/fhac-ewi/grid-optimizer/wiki/Begrifflichkeiten)
