### ISSUE TITLE
Übernahme der Trassenplanung + Wärmebedarf der Entnahmestelle von Gruppe A4

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#41]
Wir arbeiten mit Gruppe A4 zusammen. Die können uns ab Sonntag ihre Trassenplanung zur Verfügung stellen. Die muss in unserem Tool eingepflegt werden.

**Comment by einfachMel** [comment]
Ist umgesetzt bis auf die Verbindung zu 5.2(Schoßstr. 18-22 (Block 9)) und 5.3 (Poststr.)
