### ISSUE TITLE
Temperaturzeitreihen für Jülich ermitteln

### ISSUE THREAD

**Issue by V3lop5** [fhac-ewi/grid-optimizer#71]
In diese [Datei ](https://github.com/fhac-ewi/grid-optimizer/blob/main/resources/temperature-time-series.csv) mit `;` getrennt weitere Zeitreihen mit Tagesmittelwerten einfügen.

Bitte dran denken, dass das Dezimaltrennzeichen `.` ist.

Wenn weitere Zeitreihen eingetragen sind, muss [hier](https://github.com/fhac-ewi/grid-optimizer/blob/1b0142526d5d4c7d52ca74ad63706d35d53671a6/test/util/RessourceUtilTest.kt#L11) die Anzahl der verfügbaren Zeitreihen aktualisiert werden.

Bitte einen neuen Branch erstellen und hinterher einen PR erstellen. Wir wollen nichts direkt auf dem `main`-Branch pushen! 

Getestet werden kann dies nach der Anpassung mit `gradle run` und dem Besuch der Seite http://localhost:8080/api/temperature/keys

**Comment by vantu2112** [comment]
Hey Paul, Was genau soll die Datei bearbeitet werden? Wie ich verstehe wir sollen händisch diese Werte in einer neuen CSV-Datei übertragen. Und in CVS Datei steht "," für die Trennung der Spalte nicht ";" oder?

http://localhost:8080/api/temperature/keys. Dieser Link ist leider nicht erreichbar.

**Comment by V3lop5** [comment]
@vantu2112 die CSV-Datei für [Standardlastprofile](https://github.com/fhac-ewi/grid-optimizer/blob/main/resources/standard-load-profiles.csv) ist ein Beispiel für eine valide CSV-Datei mit Dezimalzahlen und mehreren Spalten. 
Kommata versuche ich immer zu vermeiden, da dies entweder als Spaltentrenner oder als Dezimaltrennzeichen gesehen werden kann.
Deshalb bitte als Dezimaltrennzeichen den Punkt verwenden und als Spaltentrennzeichen das Semikolon.

Falls du das mit Excel nicht hinbekommst, kannst du die CSV Datei nachträglich im Editor öffnen und die Zeichen ersetzen.


Der Link funktioniert nur, wenn du den Server bei dir lokal startest. `gradle run` ist der kurze Hinweis - eine vollständige Anleitung gibt es hier: https://github.com/fhac-ewi/grid-optimizer

Wenn du vernünftige Tagesmittelwerte von Jülich gefunden hast, kannst du die Quelle auch hier verlinken. Ggf hat @einfachMel  dann noch Zeit.

**Comment by V3lop5** [comment]
Ich habe hierher ein paar Daten kopiert 
http://www.ips-modelle.de/cgi-bin/pub_wetterdownload.epl

**Comment by V3lop5** [comment]
https://cdc.dwd.de/portal/shortlink/162ea076-9192-4ae5-83c0-dd0078b91282

Hier kann man sich anscheinend Tagesmittelwerte herunterladen

**Comment by einfachMel** [comment]
Die Temperaturdaten von Aachen, Köln-Bonn und Nörvenich wurden je von den Jahren 2018-2020 hinzugefügt
